// electron-builder discovers this file by name (`electron-builder.{yml,json,
// js,cjs,ts,...}` in the project directory), so `npm run dist` needs no extra
// flag. It is CommonJS because electron-builder `require`s the config before
// any TypeScript build has run.

const identity = require('./src/shared/appIdentity.json')

module.exports = {
  appId: identity.appId,
  productName: identity.productName,
  // Defaults to productName; set explicitly so the shipped binary is
  // `kizuna.exe` regardless of how the display name is capitalized.
  executableName: identity.executableName,
  directories: {
    output: 'dist'
  },
  // Stable, shell-safe release asset name.
  artifactName: '${name}-${version}-setup.${ext}',
  files: ['out/**/*'],
  extraResources: [
    { from: 'resources/mpv', to: 'mpv' },
    { from: 'resources/ffmpeg', to: 'ffmpeg' },
    { from: 'resources/mecab', to: 'mecab' },
    { from: 'resources/yt-dlp', to: 'yt-dlp' },
    { from: 'resources/icons', to: 'icons' },
    // Generated by `npm run notices`, which `npm run dist` runs
    // first — the bundled mpv and FFmpeg builds are GPL-3.0-or-later, so the
    // installer has to carry their licence texts and a source offer. The
    // generator fails closed, so this directory is either complete or the
    // packaging run never reached electron-builder.
    { from: 'build/notices', to: 'notices' }
  ],
  win: {
    target: 'nsis',
    // Local builds remain unsigned when no certificate is provided.
    signtoolOptions: {
      // Sign releases with SHA-256 and an RFC 3161 timestamp.
      signingHashAlgorithms: ['sha256'],
      rfc3161TimeStampServer: 'http://timestamp.digicert.com'
    }
  },
  nsis: {
    oneClick: false,
    allowToChangeInstallationDirectory: true
  },
  fileAssociations: [
    {
      ext: ['mkv', 'mp4', 'webm', 'avi', 'mov'],
      name: 'Video',
      role: 'Viewer'
    }
  ]
}
