// electron-builder discovers this file by name (`electron-builder.{yml,json,
// js,cjs,ts,...}` in the project directory), so `npm run dist` needs no extra
// flag. It is CommonJS because electron-builder `require`s the config before
// any TypeScript build has run.

const identity = require('./src/shared/appIdentity.json')

module.exports = {
  appId: identity.appId,
  productName: identity.productName,
  // Defaults to productName; set explicitly so the shipped binary is
  // `kizuna.exe` regardless of how the display name is capitalized.
  executableName: identity.executableName,
  directories: {
    output: 'dist'
  },
  // Generate electron-updater metadata without letting platform jobs publish
  // anything themselves (`dist` commands keep using `--publish never`).
  publish: [
    {
      provider: 'github',
      owner: 'crpcrp',
      repo: 'kizuna',
      channel: 'latest',
      releaseType: 'prerelease'
    }
  ],
  // The updater service must use this generation of electron-updater or newer.
  electronUpdaterCompatibility: '>=6.8.9',
  // Stable, shell-safe release asset name. Windows publishes a single
  // installer, so the name needs no platform segment; `linux.artifactName`
  // below overrides this because Linux emits two artifacts per architecture.
  artifactName: '${name}-${version}-setup.${ext}',
  files: ['out/**/*'],
  extraResources: [
    { from: 'resources/mpv', to: 'mpv' },
    { from: 'resources/ffmpeg', to: 'ffmpeg' },
    { from: 'resources/mecab', to: 'mecab' },
    { from: 'resources/yt-dlp', to: 'yt-dlp' },
    { from: 'resources/icons', to: 'icons' },
    // Generated by `npm run notices`, which `npm run dist` runs
    // first — the bundled mpv and FFmpeg builds are GPL-3.0-or-later, so the
    // installer has to carry their licence texts and a source offer. The
    // generator fails closed, so this directory is either complete or the
    // packaging run never reached electron-builder.
    { from: 'build/notices', to: 'notices' }
  ],
  win: {
    target: 'nsis',
    // Local builds remain unsigned when no certificate is provided.
    signtoolOptions: {
      // Sign releases with SHA-256 and an RFC 3161 timestamp.
      signingHashAlgorithms: ['sha256'],
      rfc3161TimeStampServer: 'http://timestamp.digicert.com'
    }
  },
  nsis: {
    oneClick: false,
    allowToChangeInstallationDirectory: true
  },
  linux: {
    // Both targets are x64-only: resources.lock.json pins one Linux payload
    // and it is x86-64 (see the vendor mirror's LINUX_X64_DEPENDENCIES.md).
    target: [
      { target: 'AppImage', arch: ['x64'] },
      { target: 'deb', arch: ['x64'] }
    ],
    // Reuse the app artwork already used by the Windows package.
    icon: 'build/icon.png',
    // Debian policy requires a contactable maintainer, and fpm refuses to
    // build without one. `package.json`'s `author` is a bare name, so the
    // address is given here instead of reshaping that field.
    maintainer: 'Adam Kocsis <kocsisadam1991@gmail.com>',
    // Both artifacts carry platform and architecture, so a Linux download is
    // never confusable with the Windows installer in a release listing.
    artifactName: '${name}-${version}-linux-${arch}.${ext}',
    // electron-builder writes this value to the generated desktop entry after
    // applying `desktop.entry`, so the complete category list belongs here.
    category: 'AudioVideo;Video;Player;Education',
    // Kizuna embeds mpv through X11's --wid. Supplying the backend in the
    // generated desktop entry makes a normal menu/file-manager launch work on
    // both X11 desktops and Wayland desktops through XWayland; users must not
    // have to discover and add this implementation detail themselves.
    executableArgs: ['--ozone-platform=x11'],
    synopsis: 'Video player for Japanese language learning',
    description:
      'Kizuna plays local and streamed video with mpv, tokenizes Japanese subtitles with MeCab, ' +
      'looks words up in Yomitan dictionaries, and mines vocabulary into Anki.',
    // Declared explicitly rather than derived from `fileAssociations`, which
    // carries no `mimeType` and would otherwise register private
    // `application/x-ext-mkv` types instead of the real video ones.
    mimeTypes: [
      'video/x-matroska',
      'video/mp4',
      'video/webm',
      'video/x-msvideo',
      'video/quicktime'
    ],
    // Electron derives its X11 `app_id`/WM_CLASS from `desktopName` in
    // package.json. Installing the entry under the matching filename is what
    // lets a desktop environment tie the running window to this launcher
    // (icon in the dash, window grouping) instead of showing a generic one.
    syncDesktopName: true,
    desktop: {
      entry: {
        GenericName: 'Video Player',
        Keywords: 'video;player;japanese;subtitles;mpv;anki;language;'
      }
    }
  },
  appImage: {
    // AppImage cannot install Electron's setuid sandbox helper. Preserve
    // electron-builder's default AppImage argument while adding Kizuna's X11
    // requirement (target-specific options override linux.executableArgs).
    executableArgs: ['--no-sandbox', '--ozone-platform=x11']
  },
  deb: {
    // Replaces electron-builder's default list rather than extending it, so
    // Electron's own runtime dependencies are repeated here verbatim.
    depends: [
      'libgtk-3-0',
      'libnotify4',
      'libnss3',
      'libxss1',
      'libxtst6',
      'xdg-utils',
      'libatspi2.0-0',
      'libuuid1',
      'libsecret-1-0',
      // The bundled mpv, ffmpeg, and ffprobe are unmodified executables taken
      // from these exact Ubuntu 24.04 packages, and they load their non-
      // baseline shared libraries from them. The pins are the vendor mirror's
      // documented loader policy (LINUX_X64_DEPENDENCIES.md); relaxing them to
      // a version range would let a partial upgrade break playback at runtime
      // instead of at install time. MeCab needs only the glibc/libstdc++
      // baseline and is loaded through its own relative wrapper.
      'mpv (= 0.37.0-1ubuntu4)',
      'ffmpeg (= 7:6.1.1-3ubuntu5)'
    ]
  },
  fileAssociations: [
    {
      ext: ['mkv', 'mp4', 'webm', 'avi', 'mov'],
      name: 'Video',
      role: 'Viewer'
    }
  ]
}
